language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "eS88oTGM8q7BCT9FrtDyhezc650MSERzQhv4g+xCQcu+LiQPNtQ5YQJKGwGvjNc7NH1Vcfo/sXH/KuMlAbeEeJHCD
2e04DNWhlohOYC0uZetfKPbJ4nhj2IieuLBq/il4iV8GC/4GQLt4L9sMaHZ7U5zqYmjsF40hZEhBtSY7WLyC/UY+PWShzi/Ex26X
PMSIdykJekHRvTmRARfEKvTKxzgiJyxr294WBBpIu4AsrFg++4YIl6735gox3IlCzUXOacVpFIrS30eTIUAvJKQ0eds1EBi/TqA+
POiH1bbGOKrAWvwtUJa3u8P7uPdpkoS7d6eAovycXQM2o68QUnVVqkYFainGkjqwhyT8rHf/eHapZb4ufuOy1GErKDZD81z/gKH3
qY/Gurc9QXFH+vl0NgOI33buCFIAS6EBjF9QFxiaKpKye94X2piv31lRK1RMDFaF8QlxJ2aitk8b3FqCY/VAfPiotC8JbBg7TL9j
YmTyozI8OJ0qK02Y5zIIVDGAfSOhzWSIE5Vy1nJDdiiEU9dly5uHIOva2TdqjhllYmc8+wYftbRVyyzoJ4k0E0Q0Bpc2evq1e4j1
PuxT1ad2uGX6xCqx4sDS78PjMx76tVWBRHN7/OOZG3kMglHreEp1v5YrVVIC1B9HUOMarAUf4WrR5OKsbZkipI+wfauUhw="

jdk:
  - oraclejdk8
  
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U
  
cache:
  directories:
  - $HOME/.m2

after_success:
  - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
  